# kubernetes/infrastructure/longhorn/longhorn-prereqs-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-prereqs
  namespace: argocd
  annotations:
    # Choisissez une wave qui s'exécute AVANT longhorn
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/hugz6/petra-homelab.git # Assurez-vous que c'est bien votre repo
    targetRevision: main
    path: kubernetes/infrastructure/longhorn/prereqs
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
