apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-db
  namespace: forgejo
spec:
  instances: 3
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
  storage:
    size: 5Gi
    storageClass: longhorn-single
