---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-password
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAXRldyM3R8kVdqYQpv9FKsaJFRMjrd7w2sZR6e59fZOapuooDj4S1tPDUy2STpT5qzH2IFiR7ykHX3V8VhsV8L66j4ES414cm47g6aj1BYQDv+rhX2qmCn6AoXe/9NWv1L9jjqWg86CHruVLmubFFDUjhvvsBU00vHsnnFkirMAH2uPH8jT1HUXdLye2WN9LHD1QntzwQuvVf7AQcBSR4whqB8lUgaY52UQjKs4QynURQDnjeyYEQ4nJnw4ifhtBQn2SHWx/sKsIqq14WWoqqHw+NM19VEHGrBqAv1Sfv6ChVLOQ8GG4QXMb2MS296YD7lbRM2EZBNsTDvRC8QVAmSt/HIXPXdfG4MQTi4d2rhtIJabpr2P2HsIPPlVeV4Sg0EVTmzeMlavmMNXrcDR1Ho2SGxYpNpu297SjG0GWjavxl7efDqKRY8YIOTMvUrDsW09yC8bPWfKn0e6XqzcZgwn7rRig2cV3umBQ2D7h3lwsgio84aNbnPqu2sqsfsKlxDGVYdI2jK6N2wGa+RUmm3UoStALh6PUsCCSNnWFYzPP/XZwQ9TTLxixugzE0sfLsl8RKW0PAIOv/RbaN2WRpRIuT5bbkukUT0VJ8wO6GWekB7nKFnHsKM4FnR6SZKuSDUiZOn/8K73Fem7xOVsl1PgErrf9L73ZrGtkiHPkFHIwFQetfxj8HAiYx7vWVJ420wIjuYI7lJI9IfohZ0aMiSPgXRUHSoA9LMGESSV+ee2XWLnoCH
    admin-user: AgCWHulSlApRHItiI0Cd28zCJU3Vile1/Oii9sYJjEn4RQh6bFx+EdfV3MnMWDVshUvnM4K+ntIaNTyPCDltSmJlQO5Rs/OkUJIuMjfH8vTcAzze+Gwwpjirbh7aBBvOqSqz4337T/OJDlvX6SDpL2RO+Krv3F7G0LMBfh6iFkmq0oajncEGoB5jv+OJjKFD16ikMcpO7Gv0e2pi8yNPJH6w2wNw4OuIJZkT+g0u37CtLaM7D7hfmJNnC/FkC/CjbQwy3PlrVMajl7tuaC4qyvhMEq4sGXDwK0x4+SwRsPukuy03WdhvhjoM3P2kPvwcKn4snJbsnEm/I77GJ/YZ62S52POlYlpIKqtRP+QIE7pTX9SQBo0qsyCfESf1ivbMs90SDI3IqMcw2F7BcXSUr7B5HvhQ/Uoj0lFdh5PF5kNzR2O6kFKVrlLhHz9I2Ukm2onYwBfON5+Ho+cbr3PImfp92taOwbTpBLV0qmdDsKh7qwbWGwzpFwOe+lySZq4CatSFqbQlvHQ2e/KxBORp+DexBUBHQaXgwJNjt5JDFyayIDyA9TOmyBhRtzTD3fmsY9kP13OkV/mm/8Y6hv8Fdvfu8LKuDwOQye4ADKeGo8wp02SSYBu5rehkdZ5CabCpToetQt9D5tWubCt2SRXX/Aph20HXhnmmyLmw4+ncm6fGcmXLZnmHtmvVPqZY8YxHYDyCnEF+qA==
  template:
    metadata:
      name: grafana-admin-password
      namespace: monitoring
