keys:
  - &admin age1rr52ucr5muxljaw6g844tw8jkdf60r6kllz5n922lzjueyxgc9hqh8usdf
  - &master age1wjugcvk2yxjgrw7205lhr552r5ugyemmc0mty5qc4f3l75zfr3dq4gm374
  - &node1 age1tkz9wvpzljzd7z0axxnex3qq5wrmrrxlq9cx3en6efz7npargatsr3kl28
  - &node2 age1sysrvhd8cc9u9uq4h7kze8zje5pha96733yml68fr66t0ljg85rs3j70ra

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *admin
          - *master
          - *node1
          - *node2
