replicaCount: 1

app:
  host: 0.0.0.0
  port: 80

config:
  title: "Petra Homelab"
  description: "Welcome"
  logo: "/static/logo.png"

  sections:
    - title: "Homelab Links"
      type: "links"
      items:
        - name: "ArgoCD"
          url: "https://argocd.petra.ooo"
          description: "Gitops infrastructure management"
        - name: "Proxmox PVE-1"
          url: "https://pve-1.petra.ooo:8006"
          description: "Manage datacenter pve-1"
        - name: "Proxmox PVE-2"
          url: "https://pve-2.petra.ooo:8006"
          description: "Manage datacenter pve-2"

image:
  repository: ghcr.io/hugz6/garlicdoor
  pullPolicy: IfNotPresent
  tag: "main-ea0f7f7"

imagePullSecrets: []
nameOverride: "garlicdoor"
fullnameOverride: ""

volumeMounts:
  - name: config
    mountPath: /root/.env
    subPath: .env
    readOnly: true
  - name: config
    mountPath: /root/config.yaml
    subPath: config.yaml
    readOnly: true

volumes:
  - name: config
    configMap:
      name: garlicdoor-portal-config
      items:
        - key: .env
          path: .env
        - key: config.yaml
          path: config.yaml

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
