---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-admin-secrets
  namespace: harbor
spec:
  encryptedData:
    harborAdminPassword: AgAx6+na11nHovVS47jBrcrREWkkBm1Onekdz1WT2uN6yDFmVqvLsQgD76muyb+Rf6a9VrXqRqCtu+pkmnmzQNkYJhzoHLloYBC0wgfNtrnv8kKNVrD8xc8ysC03F0td9muJGuMHgWhP4QDeUehJecdzvok20jZf32IOV/f+2Z3NDZqEp7dNC7FcVx+ZsE72nG7zJUgHTJmtIfJCORI6ojrl6NmBKebxYN3NM/gm3eEh71tFvJuFYoyalARMDV8RPkAjK/3xDZJfVT/QNRyxsqmrmoYZzf6Vx16RJ6TboMqh4WzUxBz91eLnDQaAHIVzj6X/derZnQwcqKJd9DVUTjU2i15VWE3sGgf8wgnlDQlEIBCh/QfoGyTxaJgNICVkpP0Gpq4eNpOR28pz3nLkQ3RXxygj7L5qwH143rIAqDl15y9PEfYJQ6Z6R0/64UIqjS+9KyCbOoLNebaalnhfXW8ZjQVMDICt/pIk1jkOaQKtDg5tQtZK1/7fKp0sxCDhS8DnbB9FPbMdpz1ERfu8UC+J9+PZMewvPNgFR+EH+/n8CyqzRcsB7WM+ZUmFFfBSNDEVLyr3RBbw18ovvPx+L42fPjKI6/TJqea6tD+qSScv+kCPDc9BLnCsTjwXLB5joc3p3GRf8iR4ONBN8Nbhffm+/mMrOZhSL1zPyyebBRVRMrmxy5sHE2hZ26IUZBz3zJQAeFV7kOxvZhqmJlqdIani1IgSru8zzehspLhNGHQQ5MPKC2F3
  template:
    metadata:
      name: harbor-admin-secrets
      namespace: harbor
