---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-secrets
  namespace: harbor
spec:
  encryptedData:
    secretKey: AgBpBbRDv3vdQf8Zb0q79Ymq0fAahm+y6WGVR+PMR1mPfvXcaHaTyLadWiIvqgQ9BzTyQj61MU+EbzbejpiXDMxK4WOGLwOT5an05CD1Uw+OJN2BFwtqzFCT8iaIcpFp2+VCK9gGzbl55S91jZys83OKjNj/AH5BIhN6BQYnGcSpnmm7MkGACNhp//ANHNq4X0EuGrZDHURIRtR+zffdZP1zerBCMu4owxU7XeyTjdiTW1fPGV592w57gC7eruH5x8X1OMCFdHInubWxSVLy03XaGCX0P7rnexS++9TdRGMnEi2w0dwCFEmP9Wz8w3ATviSjHxx+RWtaz4LjzVE9KqzDlEmiVnMbTIxMhWnwyuyco+m//DYfZ6tKzqOv95Op7lH7Q++4qANFRSmdmC2l6Sio4YllApI2Yy0JO3bgkz+nzokJxqD6s3wP8WMoImQTzQHJaeo+UYb7LFleJG7obW37jtVgx0IYgDjRrUhU4aTjmhp5+Y88FPYWi5aD301kmBAQ+KQgL3ifH80KZSWPQ1lCq92SDyPdbbz2IJMKYwYL1tizdOUvm9wsYPtc3KHE1e8f+Mn6t6MZaaWLdYQYUUWBnPE3JqWo4zDmX+ENiYr5UjclWRHD+HBNQ9uEXWQu7rd5wUKVbU/6q4B9oBtO/IjjpHEAMhZlq8wXQYDkORq8taP1VdZ2u5jlh8MXH5DfDAqZzh87aA0GaVUhbf2G1o2mwPZMJppWmZOA8bjDQZ6dwQ==
  template:
    metadata:
      name: harbor-secrets
      namespace: harbor
