apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "garlicdoor.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "garlicdoor.labels" . | nindent 4 }}
data:
  .env: |
    HOST={{ .Values.app.host | default "0.0.0.0" | quote }}
    PORT={{ .Values.app.port | default "80" | quote }}
    CONFIG_WATCH_INTERVAL={{ .Values.app.configWatchInterval | default "10s" | quote }}
  config.yaml: |
    title: {{ .Values.config.title | quote }}
    description: {{ .Values.config.description | quote }}
    logo: {{ .Values.config.logo | quote }}
    sections:
    {{- range .Values.config.sections }}
      - title: {{ .title | quote }}
        type: {{ .type | quote }}
        {{- if eq .type "links" }}
        items:
        {{- range .items }}
          - name: {{ .name | quote }}
            url: {{ .url | quote }}
            description: {{ .description | quote }}
        {{- end }}
        {{- else if or (eq .type "text") (eq .type "markdown") }}
        content: |
{{ .content | nindent 10 }}
        {{- end }}
    {{- end }}
