apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 8.6.2
      helm:
        releaseName: grafana
      valuesObject:
        admin:
          existingSecret: grafana-web-secret
          userKey: admin-user
          passwordKey: admin-password

        persistence:
          enabled: true
          storageClassName: longhorn
          size: 10Gi

        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.monitoring.svc.cluster.local
                access: proxy
                isDefault: true
                editable: true

        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: "default"
                orgId: 1
                folder: ""
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default

        dashboards:
          default:
            kubernetes-cluster:
              gnetId: 7249
              revision: 1
              datasource: Prometheus
            node-exporter:
              gnetId: 1860
              revision: 37
              datasource: Prometheus
            kubernetes-pods:
              gnetId: 6417
              revision: 1
              datasource: Prometheus
            kubernetes-deployment:
              gnetId: 8588
              revision: 1
              datasource: Prometheus

    - repoURL: https://github.com/hugz6/petra-homelab.git
      targetRevision: main
      path: kubernetes/apps/grafana/ingress
      directory:
        recurse: false

    - repoURL: https://github.com/hugz6/petra-homelab.git
      targetRevision: main
      path: kubernetes/apps/grafana/secret
      directory:
        recurse: false

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 3m
