apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-secret
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2" # After sealed secret
spec:
  project: default
  source:
    repoURL: https://github.com/hugz6/petra-homelab.git
    targetRevision: main
    path: kubernetes/apps/grafana/secret
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 3m
