---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    oidc.clientSecret: AgAbp742W+b7vIYnXc8UHM3BClPvLvHUIPLD0UQcSMWZEU+h+sVStCWzkk35ElvKFz6ZSJSW/ceTcP0xnK6McOpLkrMoVWpZXnOEUi0kb4D/smNXdmS72vSUzuri8jzVlNgEUhk5T8IQc6+nMB7fvOshBKnc56+XISoz/3pQSwLhIL4jGZ5YhGuRmj97obnpg5MjV2LqhbZKctOht6ROS7tuxnk0gHynevKQgARW+hE6xtXZYK5gTWkW/V1p/ROBoRjvhFpUTxC0oW37G9SwA9SeKghb8tOq/JjWd1Y1L5ACCrt8gFlQlCKRpsHmlzlrBO6m0qo0blU0SRnoLXUDdIPVUkVTD+e59ORnysUSeC0Lye8NxO048BJGD4TGBIV+RcwgrrK4rGfs8wpvo9ukITelX8fbK+RiGhwRNiTrJyEQt55T0o3+u7nVukLMfrzhhQ+cGwCV2r0gp6RFGiOayDcMnP1LGfcdyXWu3yfKLsH7ydougC/Vs7bfW7x/sCCRm7DWU+smckFFY8yXokg/jJ9z4IWYwLLP35Nj8jZsfe7Ee9RJAo5EBhJ8vtHLfsOlRx9VC22mJOY0Q6rk/NMFty3A/E5uNRzhwb52ymPIxqiIvFf1afGFuOm+i75osChEm2ldfFu9tMeHI7jbYE+ec3ibj5o2oJvxb9rZMICdS6GH8ccvROIaDNfDYU8FZnV3uWeEQNB7eXDK
  template:
    metadata:
      name: argocd-secret
      namespace: argocd
    type: Opaque
