apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.7.2
    helm:
      parameters:
        - name: preUpgradeChecker.jobEnabled
          value: "false"
      releaseName: longhorn
      valuesObject:
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 3
        defaultSettings:
          backupTarget: ""
          defaultReplicaCount: 3
          guaranteedInstanceManagerCpu: 12
        ingress:
          enabled: false
        service:
          ui:
            type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 3m
