---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frp-secret
  namespace: frp
spec:
  encryptedData:
    token: AgCdk/ranHBiZ2SymXSAbG8kV/BiNJ7xvUY42RBvba7xLFv76Ykd8kYrC3XpfKeyQQqJuYGwSmn0fOqQQlB3uB3/vuSP9R6q3kDOiHo4XFC6OJyJnQhCK8AtS3MBSw/ruM+z8CJy76t34+/7zWuYotPmA1hgHr7O7vCa+Nhb968Eybmp82kqzK5bpYDG2mDz3VpC2rav+aflJlkpWYY/WASdFBDfxmWnaWqA0O3IHh5pOCnshFjLdQlzsR/Qp7rFvJaZRWHnv9YiOxjqkKOMjYESUBikum2pZX1rIL87HaSHUOTdEWRbdlnGJBrxJLXpr4gXxI0IN3fSrlEL+dx2TSNHQzPsPPa/swuQA6ndhhAVSftuuBtjA0uE9T3BCtze3eVSvfdSOVxwTlSSvvaINtetZNe+f3gUBj+XGegwILJMr91AgPBf3Ip8j0TDyVbjjCcej220jMGuOpj25xPuNJWIfZGF/k//j3q+kNaKr6ytKYTeXxuK0vuvD0EWcC8SkAghuIXzQj66Hx3AIQZ+AXUlwojnAhwYGpEcC/fA6myNazFZfAulEOYHOLwqauwfI2VnLiCAtX4RdVV+ewR9Pv1r7yvKLNSlN8SgwZ3V664WhBPc6oEAJ1r7JYBEsvk6UiUwp5Gf2rrgDv9hDZGtGCfQ82uvR1TgL05FGdKBHydgYcDRb41ggmdGXKXwk6//I5W3+7GIc5VCso48WlFyrkwYWRg6ImIYuAIHsayL0s/0BI9zXBh1s3adPcj++I1gBG1Eqk7oIlag3VTz1Qh+A/sPMKBpzMl/x9COtddhH9/EXHm/gfQdBtDNcAgsUTqG7N10YCrH83tx4F99pd5p2LaSQX0gHF8Bj4VCl28wdT1X8A==
  template:
    metadata:
      name: frp-secret
      namespace: frp
