---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frp-secret
  namespace: frp
spec:
  encryptedData:
    token: AgAQynISv9Ko/PADyCdNHjO0p3ND1pheqVm3pdp3c+qFqfrmp652VGRI+/acdelwwiWKymz+hV/ofe6EnErnbAZvZHzas6A9UIDq1yFBYwq2IyRSU+/GSmmg5t2MATtoEuzjjXCtt+vKjdBBIP80m3euY1Jj6+qO+vXg1yGo1Vwk9FbeohJ6D4QYvuHnay1hm8vgnbV/3bHe8FdItcbmVZAd83Yxld+KZHkqpqQeSZ2wSpIqtPeFss3pLHclKsnxBF9xPeT4QQov3vj4MdPOG57rwTXzZl2ELVvy97smSfq/O0gcG8EKYtLq0bKyrLh7/xndGb5fl5lkzZHEjt4QenV5R1eqAbuTb8gFP8TiT9YmusUUKGr3Mlv2aKJYcOGp5gkz3LvEeTHyS6Bgxvqwh83y2mnQgCgzSMDzt6KPp079yTwu6V0Nnoy2YmHQx72O/lrORE6B1y5OKIRWS6olvPxUByAwQdX1PHrTsN1HKe4hpD5k6yGvYcrhgQheUFywmdZpSZ+l2x/bPiWT8JOs7QvFxO6SH+5S/OdvQ58laChtK4Fy8WX9/JPG9srpGuUrxabFkpnzskYK7RWa7PBx9syQkh3bfwGijYnhuWuH432KLYAz45E4MmWVzswtWg8Y76EFtPja/O+myMwL9u2Q3FAhAF6phxZ19204G0eiP2esTOaAStisETYvlQQ6ENji9sXJDo+yya9dGM6qOtwZ9D72OyDxIQqYnUgVDO0GCdEb8ui9yFwjqM9egxWYatsaI5jsaDfWQyiGqybngQg8znG4ZNThnu/BQbVVzW3tOl8t8/rI6cNMX8bsTeip/86sfM7YicQugL4fklXWXSRWjtsZ4BeM4nAVXlhgWdH1vMPQzA==
  template:
    metadata:
      name: frp-secret
      namespace: frp
    type: Opaque
