apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-pg
  namespace: authentik
spec:
  instances: 3
  bootstrap:
    initdb:
      database: authentik-db
      owner: authentik-root

  storage:
    size: 1Gi
    storageClass: longhorn-single