apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: 1.18.0
      helm:
        releaseName: harbor
        valueFiles:
          - $values/kubernetes/apps/harbor/values.yaml

    - repoURL: https://github.com/hugz6/petra-homelab.git
      targetRevision: main
      ref: values

    - repoURL: https://github.com/hugz6/petra-homelab.git
      targetRevision: main
      path: kubernetes/apps/harbor/secret/

  destination:
    server: https://kubernetes.default.svc
    namespace: harbor

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
