apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.11.3
    helm:
      releaseName: ingress-nginx
      valuesObject:
        controller:
          service:
            type: LoadBalancer
            annotations:
              metallb.universe.tf/loadBalancerIPs: 192.168.0.110
          ingressClassResource:
            name: nginx
            enabled: true
            default: true
          allowSnippetAnnotations: true
          config:
            use-forwarded-headers: "true"
            compute-full-forwarded-for: "true"
            use-proxy-protocol: "false"
          metrics:
            enabled: true
            serviceMonitor:
              enabled: false
          admissionWebhooks:
            enabled: true
        defaultBackend:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 3m
