---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgBkMRkKPhyCQ35/r+2E4RuwqBYAChKj2q0tzd9N1HDXBtWmqtcRE1nz4fk+w5iQGsiWpsYSq4xjgP+RTL+tujYDFqBmdDjTHz/yH9I21d40w8mqK3r2tkxQk2Gz/H2C/L+ru4TXQRuT27nijcnUvcYwE/rOQXiC6lVEE0EUDj0L4m+569kqMKIA5pRE1+Ax7/ctkRcpqyyMclUpf/wlgGhX6VJhKmiDWRrgtkfOMGA2pn96apZo2FQQtOWcrOZ6cH4hgThTIE300KJgD61jF1t+IY48VIciyWgQ6vbZpxafXO3HB6QvUBPgpKoVeh7c3Owln2DprF3+rZJ5cDY+Huf4IVXV+rH0RLWNb+rfuJ023EnH/r6+IYh/pKk9ydckDbJIIMrrTfImbRkY+LUWU/eH698Pz96wwxzkfuMQ3zE02jW056s+oNw1WNcSyGOPIPLUedYCYjMa43zeADOERSIeikqR6qEQMPqEToXvl+z3qo8EM996P/sPwEHswvSQAnE/wAF0/cwmt70H5yJYoqO/SUlUrKtn+jljxkai2P7C9m/USawNddBtLoxL3CM+KU+VtxQzBFYWr+l/CWXFsJ8OuV0WG1GG60ZgTi4+nN5rwuRDEqr4RU9y4PlmVeorH+GTMWmJ/giPHdKnLtqIS1x3ZXwVhHHlyo/+PWsOi5QRv/M/bA/XnYXKHCEy+navHsDq3mmraSyLMVjw50pC/Gdpdey/mmSuRHpC2HeaSMqpGjs2PknJd0vnZAFTuEZLJoQOhcyTvzzYXeAkXoqReZ8S5fuq1y6Oo/WPF2L5SyMyKzL042MOh8REXYg6kDhWRVPiLnyZzk71RiMWMYDQE817Kv+OMyW2c4ZE8YmMrsoRluuPuZoUHe9X7upoi0PzGGsbbFmswH/kKBPUxm5zdinnMVkOKnJYvT1YRqz2p2vm
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflare
