apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authelia-db
  namespace: authelia
spec:
  instances: 2
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: authelia
      owner: authelia
