---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAQ8V7zPO/TlR62MAgcodXEqhCxPC380jvN4vvNUdZNcvkdw8CDcYeT3a0+cu/tvMWgbRbOEGazgPKbf4a2QIPKO16ICQGnIUfPTbdLb6U3hQuXDQVfozxPol20Ds9lS9WrmwF0EZzhB06QLMjgLg7KnY9CGR1s9XFyXxPlto3GGYvj3NlJlxezEtzVqdJw0oKaftqiGKMzVC98mKNde4vQ1d5Ku/RQaKMALx2/tqQZlV6sUBGUTPtvhuINwfGLfPZbWvGZ0xYvAO8n8iISHbw90lPOwC0w5Fvu4bOF1rtCDu+fPOQARuGR7fKOFJTlRe7lgmzaDMK7MApEiOBmTUVx4MWcKv5CTNWa7l1mRwFDeLJo6LMEmrjaY+Vqn1RDviMkSKIhCNcdFNH8TMQfJeKnXF4+63kqkiDNBgr0oAEykWcWCmwe+ZLTMoRXt/bvqWknDTDQ2lcS2E4+uhNRTHNQhQN56dBqXw54MIsGm6mt0cPvKLhNvAZPe4MyPnPYiYohgV18muYeqEkhkz6KI7EXOW7HtVW+UtauBsGVXd4xFZ2I7ku8XibLSTuCfMYlFVe1ctNtPPHndLNZklbpSnFdUEaVquaUBQhBLbkOUIg+E/Ue76hrtwngaZ9y5RamK7tJwBOUzYN51LnnIwYTMiStwLncVdNrSrlQn1dsEQx8Rr51wolwE6mJ7htlwh+kv4X0W2pjhYO5xg==
    oidc-client-secret: AgAKeOIpHNk/LVg7lh++AH8vXLOZzpz93UCgoAyvhoXrq+21CqT6j0ohyNvsDlv1Ymd0E8MvXEWx8EfSDhUnNbjZUZLIi0VfpdvCGP8J95NefzrgoFBEc5r04fCF6P5Z6VFjupe8AaM7vcdYNqSNfSj+E9GY4skMGu2weBXvnhkyTN8b/4UvwiIRXgwAJNVtWK82uS6TPUdcp2dFFalh3hSaIZg/Q2YTsZcugxO8M+IuprPulYeiI7i3dGCQtngnLdzJO996y7EZifGkFerl56zT3U7WL+S9V44csCxZJ4N7Lromgl371y2gcWvb1P+77eZEcytop1te+fhHg5twGBaqreaMv1CfY7qWMz1DBVcONUlZsd5u+zAveLIEzewPNS05kC9RrQwQ3JL12xT7aZGG1lhAETbvyVOw1Q8RIdhmsEOD0I4tJwe8CEFNWyG9u4mPNooL017E7BJ7MldccekIWd/zl8yMDWaOvTQpXARunHVv3WjznoTOYDrNRTzd7RST76pa+42mb+OoYSMoN8G5bxjrmuAHi2WBd8DHx3x3xkA83yzXPAXE/V9azxRrc/uM7Gp9YDHc/oJNHQ6+iEzhjQnvtjKTLEn3Ra6LTSH8ebTCYohOu4s2Q7ZEMPYGcRO0cZW0H9CqPzuVFRq7fKcOOI93g5+T/+eXkBOUx03Q1d23QNk//Y1nn1kbWiYFRnDiCiMGWpiwKw==
  template:
    metadata:
      name: grafana-secrets
      namespace: monitoring
    type: Opaque
