---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAry/0MYOksZDNSCnXPJTLmFOQW3pIALWrz3fukuYcqLym2Z5yRXvCk+GF8DipV9JYiWX1aoXd9hqeQUvfGeB4V9NegjFjZOICyFmeYoN9+fucKqk1Z/bCT309oOqCvwYuPyh8rcI0qTxP1H329H1aUhCCEN5EKuKDOAI8W9UCSSdz79ji59KPkylTqqJm1F7Es2pSVnP1jj0jloMycsaCbYuLihb31dQ02FQi6BWZ4s0oz1MVHxUzE7Xh9BAQv8etiv5pfvXNG/h6XeAxFSPoRCmPGhffhfqPHk8W63I1fiq8KV4GGgZFfDldewJZu3bk+hAi6HqJUi1auZDgmE5+ITso/i9w12Q02LX+JGNIvz9qux5h2aUJ85jCMspXCxVJe3dooY4ALD/DGER8Ey3AcwD9VkQwloaJXbYf27lM9HMSMFmX29mrAosiFqoh6MRtO/VRY25nL/n1mBpeFn8J+Qp+ZsfzCk3ModqZ9DV+L3Ki8VVYqy9my4f9ACTaFJfNnrDuN+9VoqYcMONWPPssWc6R0wIHyM6YLJ8ZsYTZsvz7+ZnpgtRaSwvLhhnMxX4docw88Hi+UfVMS9kLpacEheJxF4pBx7KnYYm51CH2MQAOvcn54kgoUfcR1jn+K5ZuOfVBMJApeIryh4CXpnnCI4VJDCOo9XszRwyrVsvQU5gPsTIOeMLMWtnDj3BMtddhNua++e/FXbQ==
  template:
    metadata:
      name: grafana-secrets
      namespace: monitoring
    type: Opaque
