---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    AUTHENTIK_EMAIL__PASSWORD: AgBySn2+somiMOlxIM0FrAxM2lJgJFpvLW5PEkAn/ceUL/VjqfJ65fYlbrItDviBh5cttouQQ/lY+hm93CubhaCXNn/5yKhx06ZgSBKR7jrGHO6+rRmN4nLdDNnse4r/xC8W69oQ5aqsv9W2pJxx0GV2LFJjCRE19T9wM0pliIwBKU2zqfSYZ812zrj/H+cEJmYI9Yf6csXt4KP1tTtNqKf69UrigQWa5PUArRYogK1Pg6ir/fWoZSxxW5CzITLchb25b3iadiI/hh6/+RVwrtlG1YkoTtW0htfaXRMsg7BNP6LFg4yiWap8ss127OVIPbKC52gsu6hdpgUGbNqZAE+Tugb9U6RmV/cdBVGW7f5zWNJaDzT1Ki18SOTS5wpOqfK2DFsUW9+dyhHGnSddF30/CdoV7u1Z7aO9IV+lnSlpc3M+IiGp48moxvJTyR2Bjkx2RrtveA0KGxSl30f0RY9z6r+M6Q9rMRT87Kri20OQ0Rw1rKP8n9t4iuFCQl1Tykc0xZ9Sxo73IR8IKHynCFjds7Y9Xj/M/wrFey9+YnQ5OTVKMJFVHhxDBtBZZiBvvBTjfGGKfbvmN5wL2DJryI4B7lEtsZFLidkc7fjagHmQ/rvO9oesa/o7R1eYhd/FDmXeK/GSHksBrYrlplCZmBU6dWumdAFBoEp/WGqzgVKzK4BJiCwq6Xcr+dSiIQf+cZF/OrPHM1BhPZmrYOgnRKsIy5ShPyaw35lM/g==
    AUTHENTIK_SECRET_KEY: AgCLKm4tONKIxU9YOID/jrhIpgPqyaNLU+z3NbJJqSH404Ik24gRUfBrqzRfazVNximnu6kEdPc4lfBLNoPgEAyp61BXWaAkIpbvhN01h1F85HVLQ8hD6GTPNqSKdvM1s0z5HCcsfEpSaj0p27AequG8OBIrHs1rJ6oh9kHEU1mwxoJ/UnJwJX2MRCfA+5rcvA5aOcL5jaXHN6y6qA1mg908hIMhVyL/GGC/PJl5M0ab5UuEIv+RFkHejdu2BA9rA4bMG1iQd5XGzgm1lceGrEQMJ4JPh47Vkco+w4GZctvJKH8W/cCmRjtvNJfhnICRh45Uixc6jGxw7AyyD0xQzDSrwzjR+XefittWOAFOkacwZ9vXCvFrJhCXhJby8+JYGp4mnkuGDmYg98ljEmK6s0xSTkEf6u0KVHSbsLWelGIxruFpTUtv8HEK8mlKG/KmA1+M9qDqdXM66QG+hPpJTTYMMQGiXkPDwfY5KnMjpBEPfmyK1RB4SyvuFDaitQx9Bsi+jD9qYMqfVa1Nt6YLyyOs4PdKimeOy8YBhQfJrPY7BXDMv/BQVivapzYI7asOnbUwDk3ffig7P3keuFRN30XBE/eWxZN3CR1d5s39HpTj8aMaQY47ZSf0OYE+mZCVGJf7qS4woKma87sgl+QIuigYgbhDEQcT0H+f/Xy1aTC4yoZvVJ+YUmPtz+hftcjjl99V+AknrSP+dsEcVCFWPwIjHztyQSuBwwMGhMUxKdRocQF12P8wZnrb568qJ0ZQ9YdA971meynSCx1gCisyr99l
  template:
    metadata:
      name: authentik-secrets
      namespace: authentik
    type: Opaque
