persistence:
  defaultClass: true
  defaultClassReplicaCount: 3

defaultSettings:
  backupTarget: ""
  defaultReplicaCount: 3
  guaranteedInstanceManagerCpu: 12
  createDefaultDiskLabeledNodes: true
  defaultDataPath: /var/lib/longhorn
  replicaSoftAntiAffinity: false
  storageOverProvisioningPercentage: 200
  storageMinimalAvailablePercentage: 25
  upgradeChecker: true
  defaultLonghornStaticStorageClass: longhorn-static
  backupstorePollInterval: 300
  taintToleration: ""
  systemManagedComponentsNodeSelector: ""
  priorityClass: ""
  autoSalvage: true
  disableSchedulingOnCordonedNode: true
  replicaZoneSoftAntiAffinity: true
  volumeAttachmentRecoveryPolicy: wait
  nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
  mkfsExt4Parameters: ""

ingress:
  enabled: false
